pyLsdのエラーのインストール方法
kod-source/image_processing pull request #24
Opened 2022-12-09 04:42 UTC by nguyenanh848292

## 概要
ImportError: cannot import name 'lsd' from 'lsd'

## 実装内容
- [ ]
- Install following command: pip install opencv-contrib-python`

## 実行結果

## その他

2022-12-09 04:44 UTC, kod-source requested changes
今のREADME.mdを見ると画像のように変になるから修正してほしい
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/74532799/206625710-e0037994-d3c1-4c63-88b9-dc559a468a7a.png">

2022-12-09 04:44 UTC, kod-source commented
マークダウンの書き方を調べたら色々わかると思う

2022-12-09 04:59 UTC, kod-source requested changes
修正よろです！

2022-12-09 04:59 UTC, kod-source commented on README.md
> +pip install opencv-contrib-python
コマンドを書くときは`バッククォート`で囲って書いて欲しい
こんな感じの見た目になる
<img width="934" alt="image" src="https://user-images.githubusercontent.com/74532799/206627320-bf65ffea-072f-4571-a9c5-ff8173e544bb.png">

2022-12-09 04:59 UTC, kod-source commented on README.md
> +### ImportError: cannot import name 'lsd' from 'lsd'
エラー分だけだと分かりずらいから
このエラーが出たら下記のコマンドを入力するみたいなことを書いてほしい

2022-12-12 09:23 UTC, kod-source requested changes
https://github.com/kod-source/image_processing/pull/24/files#r1044090307
この修正もしてほしい

2022-12-14 06:49 UTC, kod-source commented on README.md
> +pip install opencv-contrib-python
@nguyenanh848292 
> pip install opencv-contrib-python

てか今思ったけど、このコマンドで治ったってことだと思うけど、このコマンドはopen cvをインストールするときに使用するコマンドだから今回の事例とは異なる気がするよな🤔
↓の画像の下のコマンドと一緒だからなんか勘違いしていると思う。
ごめんやけど、もう一回確認してほしい！！
<img width="1095" alt="image" src="https://user-images.githubusercontent.com/74532799/207525882-669791a6-27f1-4c19-a2cd-4c109a07bc39.png">

2022-12-26 07:22 UTC, nguyenanh848292 commented on README.md
> +pip install opencv-contrib-python
自分のパソコンの環境でどうやってエラーをfixしたか、曖昧になっちゃったが、lsdインストールした後、ImportError: cannot import name 'lsd' from 'lsd'　というエラーメッセージが出た記憶があるので

2022-12-26 07:43 UTC, kod-source commented on README.md
> +pip install opencv-contrib-python
lsdのインストール後に`ImportError: cannot import name 'lsd' from 'lsd'`のエラーが出たというのは理解しているし、それは問題ない。
ただ、今回はそのエラーが出た時のfix方法で`pip install opencv-contrib-python`ってなってるけど、それはopencvのインストールコマンドだから今回のエラーの修正とは関係ないって話。
多分違うコマンドでうまく行った感じだと思うからそれをもう一度見直してほしい🙏

2023-06-30 13:18 UTC, closed without merging